<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Untitled Form</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Aggiungi utente</a></h1>
		<form id="form_49809" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Aggiungi utente</h2>
			<p>Form di inserimento informazioni nuovo utente.</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Nome Utente</label>
		<span>
			<input id="element_1_1" name= "element_1_1" class="element text" maxlength="255" size="8" value=""/>
			<label>Nome</label>
		</span>
		<span>
			<input id="element_1_2" name= "element_1_2" class="element text" maxlength="255" size="14" value=""/>
			<label>Cognome</label>
		</span><p class="guidelines" id="guide_1"><small>Nome e cognome dell'utente.
Nota che verrà usato nella costruzione dell'indirizzo email per le comunicazioni: nome.cognome@ilc.cnr.it</small></p> 
		</li>		<li id="li_2" >
		<label class="description" for="element_2">Username </label>
		<div>
			<input id="element_2" name="element_2" class="element text medium" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_2"><small>Username di accesso</small></p> 
		</li>		<li id="li_3" >
		<label class="description" for="element_3">Password </label>
		<div>
			<input id="element_3" name="element_3" class="element text medium" type="text" maxlength="255" value=""/> 
		</div><p class="guidelines" id="guide_3"><small>Password di accesso</small></p> 
		</li>		<li id="li_4" >
		<label class="description" for="element_4">Ruolo </label>
		<div>
		<select class="element select medium" id="element_4" name="element_4"> 
			<option value="" selected="selected"></option>
<option value="1" >User</option>
<option value="2" >Admin</option>

		</select>
		</div><p class="guidelines" id="guide_4"><small>Ruolo dell'utente:
- User: solo inserimento/modifica delle proprie richieste
- Admin: amministratore di tutte le richieste</small></p> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="49809" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>